import os
from fastapi import FastAPI
import uvicorn

app = FastAPI()

@app.get("/")
def read_root():
    return {"message": "Hello, World!"}

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 2000))  # Usa a porta do Render ou 8000 como padrão
    uvicorn.run(app, host="0.0.0.0", port=port)

web: uvicorn app.main:app --host 0.0.0.0 --port $PORT
